Repository exercism/cpp, pull requests merged in 2023-07, with the labels that each got.

#649 [Concept] Docs - Classes
  concepts/classes/.meta/config.json
  concepts/classes/about.md
  concepts/classes/introduction.md
  concepts/classes/links.json
  config.json
Labels: help wanted, x:action/proofread, x:module/concept, x:type/content, x:rep/large

#652 [Concept] Exercise - Classes
  config.json
  exercises/concept/ellens-alien-game/.docs/hints.md
  exercises/concept/ellens-alien-game/.docs/instructions.md
  exercises/concept/ellens-alien-game/.docs/introduction.md
  exercises/concept/ellens-alien-game/.docs/introduction.md.tpl
  exercises/concept/ellens-alien-game/.meta/config.json
  exercises/concept/ellens-alien-game/.meta/design.md
  exercises/concept/ellens-alien-game/.meta/exemplar.cpp
  exercises/concept/ellens-alien-game/CMakeLists.txt
  exercises/concept/ellens-alien-game/ellens_alien_game.cpp
  exercises/concept/ellens-alien-game/ellens_alien_game_test.cpp
  exercises/concept/ellens-alien-game/test/catch.hpp
  exercises/concept/ellens-alien-game/test/tests-main.cpp
Labels: help wanted, x:action/create, x:action/proofread, x:module/concept-exercise, x:size/large

#655 Sort featured July #12in23 exercises into the tree
  config.json
Labels: x:action/improve, x:type/coding, x:rep/medium

#656 [Improvement] Add information for featured exercises
  exercises/practice/allergies/.docs/instructions.append.md
  exercises/practice/high-scores/.docs/instructions.append.md
Labels: x:action/improve, x:action/proofread, x:size/medium

#658 [Concept] Make the tree public
  config.json
Labels: x:rep/small

#659 [Improve] Link practice exercises to syllabus
  config.json
Labels: help wanted, x:module/practice-exercise, x:rep/medium

#661 [Fix] typo in classes concept
  concepts/classes/about.md
  concepts/classes/introduction.md
  exercises/concept/ellens-alien-game/.docs/introduction.md
Labels: x:action/fix, x:rep/tiny

#664 [Fix] Concept - Loops: floating point testing
  exercises/concept/interest-is-interesting/interest_is_interesting_test.cpp
Labels: x:module/concept-exercise, x:type/coding, x:rep/small

#663 [Concept] Docs - References
  concepts/references/.meta/config.json
  concepts/references/about.md
  concepts/references/introduction.md
  concepts/references/links.json
  config.json
Labels: help wanted, x:action/proofread, x:rep/medium

#665 Update introduction.md
  concepts/strings/introduction.md
Labels: x:rep/tiny

#667 [Concept] Exercise - References
  config.json
  exercises/concept/election-day/.docs/hints.md
  exercises/concept/election-day/.docs/instructions.md
  exercises/concept/election-day/.docs/introduction.md
  exercises/concept/election-day/.docs/introduction.md.tpl
  exercises/concept/election-day/.meta/config.json
  exercises/concept/election-day/.meta/design.md
  exercises/concept/election-day/.meta/exemplar.cpp
  exercises/concept/election-day/CMakeLists.txt
  exercises/concept/election-day/election_day.cpp
  exercises/concept/election-day/election_day_test.cpp
  exercises/concept/election-day/test/catch.hpp
  exercises/concept/election-day/test/tests-main.cpp
Labels: x:action/proofread, x:module/concept-exercise, x:type/content, x:rep/large

#669 [Concept] Docs - Enumerations
  concepts/enums/.meta/config.json
  concepts/enums/about.md
  concepts/enums/introduction.md
  concepts/enums/links.json
  config.json
Labels: help wanted, x:action/proofread, x:module/concept, x:rep/large

#690 [Improve] String find example
  concepts/strings/introduction.md
  exercises/concept/log-levels/.docs/introduction.md
Labels: enhancement, x:rep/small

#691 [Improve] Make fully qualified string type name explicit
  concepts/strings/introduction.md
  exercises/concept/log-levels/.docs/introduction.md
Labels: x:action/proofread, x:module/concept, x:rep/small

#685 Convert `average_run_time` to an integer
  config.json
Labels: x:size/tiny
