Repository exercism/cpp, pull requests merged in 2023-06, with the labels that each got.

#615 Concept docs for "comparisons"
  concepts/comparisons/.meta/config.json
  concepts/comparisons/about.md
  concepts/comparisons/introduction.md
  concepts/comparisons/links.json
  config.json
Labels: help wanted, x:action/proofread, x:module/concept, x:type/content, x:size/medium, x:rep/medium

#620 [Concept] Docs and Exe - If Statements
  concepts/if-statements/.meta/config.json
  concepts/if-statements/about.md
  concepts/if-statements/introduction.md
  concepts/if-statements/links.json
  config.json
  exercises/concept/vehicle-purchase/.docs/hints.md
  exercises/concept/vehicle-purchase/.docs/instructions.md
  exercises/concept/vehicle-purchase/.docs/introduction.md
  exercises/concept/vehicle-purchase/.docs/introduction.md.tpl
  exercises/concept/vehicle-purchase/.meta/config.json
  exercises/concept/vehicle-purchase/.meta/design.md
  exercises/concept/vehicle-purchase/.meta/exemplar.cpp
  exercises/concept/vehicle-purchase/.meta/exemplar.h
  exercises/concept/vehicle-purchase/CMakeLists.txt
  exercises/concept/vehicle-purchase/test/catch.hpp
  exercises/concept/vehicle-purchase/test/tests-main.cpp
  exercises/concept/vehicle-purchase/vehicle_purchase.cpp
  exercises/concept/vehicle-purchase/vehicle_purchase.h
  exercises/concept/vehicle-purchase/vehicle_purchase_test.cpp
Labels: x:action/proofread, x:module/concept, x:type/content, x:size/large, x:rep/large

#623 [Fix] String/Include Concept exercise order
  config.json
Labels: x:action/fix, x:size/tiny, x:rep/tiny

#618 [Concept] Exercise - Booleans
  config.json
  exercises/concept/pacman-rules/.docs/hints.md
  exercises/concept/pacman-rules/.docs/instructions.md
  exercises/concept/pacman-rules/.docs/introduction.md
  exercises/concept/pacman-rules/.docs/introduction.md.tpl
  exercises/concept/pacman-rules/.meta/config.json
  exercises/concept/pacman-rules/.meta/design.md
  exercises/concept/pacman-rules/.meta/exemplar.cpp
  exercises/concept/pacman-rules/CMakeLists.txt
  exercises/concept/pacman-rules/pacman_rules.cpp
  exercises/concept/pacman-rules/pacman_rules_test.cpp
  exercises/concept/pacman-rules/test/catch.hpp
  exercises/concept/pacman-rules/test/tests-main.cpp
Labels: x:action/proofread, x:type/content, x:size/medium, x:rep/medium

#626 [Fix] Concept - Boolean (content for about.md)
  concepts/booleans/about.md
Labels: x:action/fix, x:size/tiny, x:rep/tiny

#631 WIP: perfect-numbers
  config.json
  exercises/practice/perfect-numbers/.docs/instructions.md
  exercises/practice/perfect-numbers/.meta/config.json
  exercises/practice/perfect-numbers/.meta/example.cpp
  exercises/practice/perfect-numbers/.meta/example.h
  exercises/practice/perfect-numbers/.meta/tests.toml
  exercises/practice/perfect-numbers/CMakeLists.txt
  exercises/practice/perfect-numbers/perfect_numbers.cpp
  exercises/practice/perfect-numbers/perfect_numbers.h
  exercises/practice/perfect-numbers/perfect_numbers_test.cpp
  exercises/practice/perfect-numbers/test/catch.hpp
  exercises/practice/perfect-numbers/test/tests-main.cpp
Labels: x:size/medium, x:rep/medium

#628 [Concept] Docs - Loops
  concepts/loops/.meta/config.json
  concepts/loops/about.md
  concepts/loops/introduction.md
  concepts/loops/links.json
  config.json
Labels: x:module/concept, x:type/content, x:size/large, x:rep/large

#633 [Fix] Approach formatting
  exercises/practice/binary-search/.approaches/config.json
  exercises/practice/pangram/.approaches/config.json
  exercises/practice/secret-handshake/.approaches/config.json
  exercises/practice/sieve/.approaches/config.json
Labels: x:action/fix, x:rep/small

#640 [Concept] Exercise - Loops
  config.json
  exercises/concept/interest-is-interesting/.docs/hints.md
  exercises/concept/interest-is-interesting/.docs/instructions.md
  exercises/concept/interest-is-interesting/.docs/introduction.md
  exercises/concept/interest-is-interesting/.docs/introduction.md.tpl
  exercises/concept/interest-is-interesting/.meta/config.json
  exercises/concept/interest-is-interesting/.meta/design.md
  exercises/concept/interest-is-interesting/.meta/exemplar.cpp
  exercises/concept/interest-is-interesting/CMakeLists.txt
  exercises/concept/interest-is-interesting/interest_is_interesting.cpp
  exercises/concept/interest-is-interesting/interest_is_interesting_test.cpp
  exercises/concept/interest-is-interesting/test/catch.hpp
  exercises/concept/interest-is-interesting/test/tests-main.cpp
Labels: help wanted, x:action/create, x:action/proofread, x:module/concept-exercise, x:type/content, x:rep/large

#639 [Exercise] High-Scores
  config.json
  exercises/practice/high-scores/.docs/instructions.append.md
  exercises/practice/high-scores/.docs/instructions.md
  exercises/practice/high-scores/.meta/config.json
  exercises/practice/high-scores/.meta/example.cpp
  exercises/practice/high-scores/.meta/example.h
  exercises/practice/high-scores/CMakeLists.txt
  exercises/practice/high-scores/high_scores.cpp
  exercises/practice/high-scores/high_scores.h
  exercises/practice/high-scores/high_scores_test.cpp
  exercises/practice/high-scores/test/catch.hpp
  exercises/practice/high-scores/test/tests-main.cpp
Labels: x:action/create, x:action/proofread, x:knowledge/elementary, x:module/practice-exercise, x:type/content, x:rep/large

#648 [Practice Exercise Link Sweep]: Corrected links in `High Scores`
  exercises/practice/high-scores/.docs/instructions.append.md
Labels: x:rep/small
