Repository exercism/cpp, pull requests merged in 2024-01, with the labels that each got.

#754 fix typo in comparison operators example
  concepts/comparisons/about.md
Labels: x:action/fix, x:type/docs, x:rep/tiny

#756 fix(lasagna): typo in test file
  exercises/concept/lasagna/lasagna_test.cpp
Labels: x:action/fix, x:rep/tiny

#757 Sync fetch-configlet.ps1 script
  bin/fetch-configlet.ps1
Labels: x:size/tiny

#764 feat: add resistor-color exercise
  config.json
  exercises/practice/resistor-color/.docs/instructions.md
  exercises/practice/resistor-color/.meta/config.json
  exercises/practice/resistor-color/.meta/example.cpp
  exercises/practice/resistor-color/.meta/example.h
  exercises/practice/resistor-color/.meta/tests.toml
  exercises/practice/resistor-color/CMakeLists.txt
  exercises/practice/resistor-color/resistor_color.cpp
  exercises/practice/resistor-color/resistor_color.h
  exercises/practice/resistor-color/resistor_color_test.cpp
  exercises/practice/resistor-color/test/catch.hpp
  exercises/practice/resistor-color/test/tests-main.cpp
Labels: x:module/practice-exercise

#766 feat: add resistor-color-duo practice exercise
  config.json
  exercises/practice/resistor-color-duo/.docs/instructions.md
  exercises/practice/resistor-color-duo/.meta/config.json
  exercises/practice/resistor-color-duo/.meta/example.cpp
  exercises/practice/resistor-color-duo/.meta/example.h
  exercises/practice/resistor-color-duo/.meta/tests.toml
  exercises/practice/resistor-color-duo/CMakeLists.txt
  exercises/practice/resistor-color-duo/resistor_color_duo.cpp
  exercises/practice/resistor-color-duo/resistor_color_duo.h
  exercises/practice/resistor-color-duo/resistor_color_duo_test.cpp
  exercises/practice/resistor-color-duo/test/catch.hpp
  exercises/practice/resistor-color-duo/test/tests-main.cpp
Labels: x:module/practice-exercise

#760 feat(leap): add performance article
  exercises/practice/leap/.articles/config.json
  exercises/practice/leap/.articles/performance/.gitignore
  exercises/practice/leap/.articles/performance/benchmark/leap_benchmark.cpp
  exercises/practice/leap/.articles/performance/content.md
  exercises/practice/leap/.articles/performance/snippet.md
Labels: x:type/docs

#772 Update introduction.md
  concepts/vector-arrays/introduction.md
  exercises/concept/making-the-grade/.docs/introduction.md
Labels: x:type/docs, x:rep/tiny

#780 Write "approaches" for reverse-string
  exercises/practice/reverse-string/.approaches/config.json
  exercises/practice/reverse-string/.approaches/direct-construction/content.md
  exercises/practice/reverse-string/.approaches/direct-construction/snippet.txt
  exercises/practice/reverse-string/.approaches/divide-and-conquer/content.md
  exercises/practice/reverse-string/.approaches/divide-and-conquer/snippet.txt
  exercises/practice/reverse-string/.approaches/introduction.md
  exercises/practice/reverse-string/.approaches/iterative/content.md
  exercises/practice/reverse-string/.approaches/iterative/snippet.txt
  exercises/practice/reverse-string/.approaches/linear-recursion/content.md
  exercises/practice/reverse-string/.approaches/linear-recursion/snippet.txt
  exercises/practice/reverse-string/.approaches/over-engineered/content.md
  exercises/practice/reverse-string/.approaches/over-engineered/snippet.txt
  exercises/practice/reverse-string/.approaches/stack-operations/content.md
  exercises/practice/reverse-string/.approaches/stack-operations/snippet.txt
  exercises/practice/reverse-string/.approaches/swapping-characters/content.md
  exercises/practice/reverse-string/.approaches/swapping-characters/snippet.txt
  exercises/practice/reverse-string/.approaches/using-the-standard-lib/content.md
  exercises/practice/reverse-string/.approaches/using-the-standard-lib/snippet.txt
Labels: x:action/create, x:action/improve, x:action/proofread, x:type/content

#778 leap: sync
  exercises/practice/leap/.docs/introduction.md
  exercises/practice/leap/.meta/config.json
Labels: x:size/tiny

#781 reverse-string: sync
  exercises/practice/reverse-string/.docs/instructions.md
  exercises/practice/reverse-string/.docs/introduction.md
  exercises/practice/reverse-string/.meta/config.json
Labels: x:size/tiny

#777 Update introduction.md
  concepts/comparisons/introduction.md
  exercises/concept/vehicle-purchase/.docs/introduction.md
Labels: x:rep/tiny

#791 fix(concepts): correct task grouping in doctor data
  exercises/concept/doctor-data/doctor_data_test.cpp
Labels: x:rep/tiny

#790 raindrops: sync
  exercises/practice/raindrops/.docs/instructions.md
  exercises/practice/raindrops/.docs/introduction.md
Labels: x:size/tiny
