Repository exercism/cpp, pull requests merged in 2024-04, with the labels that each got.

#853 sieve: sync
  exercises/practice/sieve/.docs/instructions.md
Labels: x:size/tiny

#854 two-fer: sync
  exercises/practice/two-fer/.docs/instructions.md
  exercises/practice/two-fer/.docs/introduction.md
Labels: x:size/tiny

#847 feat: add literals concept
  concepts/literals/.meta/config.json
  concepts/literals/about.md
  concepts/literals/introduction.md
  concepts/literals/links.json
  config.json
Labels: x:action/create, x:module/concept, x:type/content, x:size/large

#859 minesweeper: sync
  exercises/practice/minesweeper/.docs/instructions.md
  exercises/practice/minesweeper/.docs/introduction.md
Labels: x:size/tiny

#860 dnd-character: sync
  exercises/practice/dnd-character/.docs/instructions.md
  exercises/practice/dnd-character/.docs/introduction.md
Labels: x:size/tiny

#788 Add practice exercise Zebra Puzzle
  config.json
  exercises/practice/zebra-puzzle/.docs/instructions.md
  exercises/practice/zebra-puzzle/.docs/introduction.md
  exercises/practice/zebra-puzzle/.meta/config.json
  exercises/practice/zebra-puzzle/.meta/example.cpp
  exercises/practice/zebra-puzzle/.meta/example.h
  exercises/practice/zebra-puzzle/.meta/tests.toml
  exercises/practice/zebra-puzzle/CMakeLists.txt
  exercises/practice/zebra-puzzle/test/catch.hpp
  exercises/practice/zebra-puzzle/test/tests-main.cpp
  exercises/practice/zebra-puzzle/zebra_puzzle.cpp
  exercises/practice/zebra-puzzle/zebra_puzzle.h
  exercises/practice/zebra-puzzle/zebra_puzzle_test.cpp
Labels: x:module/practice-exercise, x:rep/large
